### ISSUE TITLE
Difference between "Archive output path" and "Archive path"

### ISSUE THREAD

**Issue by aidanheerdegen** [aekiss/run_summary#33]
@utkarshgupta95 pointed out that `01deg_jra55v13_ryf9091` doesn't have "Archive output path"

```yaml
paths:
    Archive path: /scratch/v45/amh157/access-om2/archive/01deg_jra55v13_ryf9091
    Control path: /home/157/amh157/payu/01deg_jra55v13_ryf9091
    Output path: /g/data/ik11/outputs/access-om2-01/01deg_jra55v13_ryf9091/output372
    Restart path: null
    Sync output path: /g/data/ik11/outputs/access-om2-01/01deg_jra55v13_ryf9091/output372
    Sync path: /g/data/ik11/outputs/access-om2-01/01deg_jra55v13_ryf9091
```
but `01deg_jra55v140_iaf_cycle4` does:
```yaml
  paths:
    Archive output path: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4/output732
    Archive path: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4
    Control path: /home/156/aek156/payu/01deg_jra55v140_iaf_cycle4
    Output path: /g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf_cycle4/output732
    Restart path: null
    Sync output path: /g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf_cycle4/output732
    Sync path: /g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf_cycle4
```

What is the difference between them, and what circumstances does "Archive output path" not exist?
